CREATE TABLE APPOINTMENTS (
  APPOINTMENT_ID   VARCHAR(128) NOT     NULL,
  STATUS           CHAR(20)     NOT     NULL,
  COURSE           VARCHAR(128) NOT     NULL,
  TUTOR_ID         VARCHAR(128) NOT     NULL,
  STUDENT_ID       VARCHAR(128) NOT     NULL,
  APPOINTMENT_DATE CHAR(20)     NOT     NULL,
  APPOINTMENT_TIME CHAR(20)     NOT     NULL,
  PLACES           MEDIUMTEXT   NULL,
  CONSTRAINT       PK           PRIMARY KEY (APPOINTMENT_ID),
  CONSTRAINT       TUTORFK      FOREIGN KEY (TUTOR_ID)   REFERENCES TUTOR(ACC_NO),
  CONSTRAINT       STUDENTFK    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ACC_NO)
)
