CREATE TABLE `APPOINTMENTS` (
  `APPOINTMENT_ID` varchar(128) NOT NULL,
  `STATUS` char(20) NOT NULL,
  `COURSE` varchar(128) NOT NULL,
  `TUTOR_ID` varchar(128) NOT NULL,
  `STUDENT_ID` varchar(128) NOT NULL,
  `APPOINTMENT_DATE` char(20) NOT NULL,
  `APPOINTMENT_TIME` char(20) NOT NULL,
  `PLACE` mediumtext NOT NULL,
  PRIMARY KEY (`APPOINTMENT_ID`),
  KEY `TUTORFK` (`TUTOR_ID`),
  KEY `STUDENTFK` (`STUDENT_ID`),
  CONSTRAINT `STUDENTFK` FOREIGN KEY (`STUDENT_ID`) REFERENCES `STUDENT` (`ACC_NO`),
  CONSTRAINT `TUTORFK` FOREIGN KEY (`TUTOR_ID`) REFERENCES `TUTOR` (`ACC_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
