CREATE TABLE MESSAGES (
  MSG_ID VARCHAR(128) NOT NULL, 
  TUTOR VARCHAR(128) NOT NULL,
  STUDENT VARCHAR(128) NOT NULL,
  MESSAGE MEDIUMTEXT NOT NULL,
  TIME BIGINT NOT NULL,
  SENDER CHAR(10) NOT NULL,
  CONSTRAINT PK PRIMARY KEY(MSG_ID),
  CONSTRAINT FK1 FOREIGN KEY (TUTOR) REFERENCES TUTOR(ACC_NO),
  CONSTRAINT FK2 FOREIGN KEY (STUDENT) REFERENCES STUDENT(ACC_NO)
);
