CREATE TABLE `MESSAGES` (
  `MSG_ID` varchar(128) NOT NULL,
  `TUTOR` varchar(128) NOT NULL,
  `STUDENT` varchar(128) NOT NULL,
  `MESSAGE` mediumtext NOT NULL,
  `TIME` bigint(20) NOT NULL,
  `SENDER` char(10) NOT NULL,
  PRIMARY KEY (`MSG_ID`),
  KEY `FK1` (`TUTOR`),
  KEY `FK2` (`STUDENT`),
  CONSTRAINT `FK1` FOREIGN KEY (`TUTOR`) REFERENCES `TUTOR` (`ACC_NO`),
  CONSTRAINT `FK2` FOREIGN KEY (`STUDENT`) REFERENCES `STUDENT` (`ACC_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
