CREATE TABLE PARENT (
  ACC_NO VARCHAR(100) NOT NULL,
  FNAME VARCHAR(100) NOT NULL,
  LNAME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  CONSTRAINT PARENT_PK PRIMARY KEY (ACC_NO)
)
