CREATE TABLE `PARENT` (
  `ACC_NO` varchar(128) NOT NULL,
  `FNAME` varchar(128) NOT NULL,
  `LNAME` varchar(128) NOT NULL,
  `EMAIL` varchar(128) NOT NULL,
  `PASSWORD` varchar(128) NOT NULL,
  PRIMARY KEY (`ACC_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
