CREATE TABLE `PARENT` (
  `ACC_NO` varchar(100) NOT NULL,
  `FNAME` varchar(100) NOT NULL,
  `LNAME` varchar(100) NOT NULL,
  `EMAIL` varchar(100) NOT NULL,
  `PASSWORD` varchar(100) NOT NULL,
  PRIMARY KEY (`ACC_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1