CREATE TABLE STUDENT (
  ACC_NO VARCHAR(100) NOT NULL,
  FNAME VARCHAR(100) NOT NULL,
  LNAME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  GENDER CHAR(1) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  PARRENT_ACC_NO VARCHAR(100) NOT NULL,
  CONSTRAINT STUDENT_PK PRIMARY KEY (ACC_NO),
  CONSTRAINT PARENT_FK FOREIGN KEY (PARRENT_ACC_NO) REFERENCES PARENT(ACC_NO)
)
