CREATE TABLE `STUDENT` (
  `ACC_NO` varchar(128) NOT NULL,
  `FNAME` varchar(128) NOT NULL,
  `LNAME` varchar(128) NOT NULL,
  `EMAIL` varchar(128) NOT NULL,
  `GENDER` char(1) DEFAULT NULL,
  `BIO` mediumtext,
  `PASSWORD` varchar(128) NOT NULL,
  `PARENT_ACC_NO` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`ACC_NO`),
  KEY `PARENT_FK` (`PARENT_ACC_NO`),
  CONSTRAINT `PARENT_FK` FOREIGN KEY (`PARENT_ACC_NO`) REFERENCES `PARENT` (`ACC_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
