CREATE TABLE TUTOR (
  ACC_NO   VARCHAR(100) NOT NULL,
  FNAME    VARCHAR(100) NOT NULL,
  LNAME    VARCHAR(100) NOT NULL,
  EMAIL    VARCHAR(100) NOT NULL,
  GENDER   CHAR(1) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  BIO VARCHAR(4096) NOT NULL,
  CONSTRAINT TUTOR_PK PRIMARY KEY (ACC_NO)
);
